-- Add email column to guests table (optional, for sending QR via email)
alter table if exists public.guests
  add column if not exists email text,
  add column if not exists qr_sent_at timestamptz;

-- Email logs table for tracking delivery status
create table if not exists public.email_logs (
  id bigint generated by default as identity primary key,
  guest_id bigint references public.guests(id) on delete cascade,
  acara_id bigint references public.events(id) on delete cascade,
  email_to text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.email_logs enable row level security;

-- RLS: authenticated users can read email logs
create policy "Authenticated can read email_logs"
  on public.email_logs for select
  to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'panitia'))
  );

-- RLS: admin can insert email_logs
create policy "Admin can insert email_logs"
  on public.email_logs for insert
  to authenticated
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );
