-- Buku Tamu Digital - Supabase Schema
-- Run this in Supabase SQL Editor
-- Safe to re-run on existing database (IF NOT EXISTS)

-- 1. PROFILES (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  role text not null default 'scanner' check (role in ('admin', 'scanner', 'staff')),
  display_name text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

-- 2. EVENTS
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  nama_acara text not null,
  slug text not null unique,
  lokasi text not null,
  tanggal_mulai date not null,
  tanggal_selesai date not null,
  jam_mulai time not null,
  jam_selesai time not null default '17:00',
  grace_period_minutes int not null default 30,
  status text not null default 'akan_datang' check (status in ('akan_datang', 'registrasi_dibuka', 'registrasi_ditutup')),
  total_tamu int default 0,
  created_at timestamptz default now(),
  created_by uuid references public.profiles(id)
);

alter table public.events enable row level security;

create index if not exists idx_events_status on public.events(status);
create index if not exists idx_events_slug on public.events(slug);

-- 3. GUESTS
create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  nama text not null,
  instansi text not null,
  no_hp text,
  tujuan text,
  kategori_tamu text not null default 'reguler' check (kategori_tamu in ('reguler', 'vip', 'vvip')),
  status_kehadiran text not null default 'tidak_hadir' check (status_kehadiran in ('hadir', 'terlambat', 'tidak_hadir')),
  waktu_kedatangan timestamptz,
  waktu_registrasi timestamptz default now(),
  created_at timestamptz default now(),
  acara_id bigint references public.events(id) on delete cascade,
  qr_token text not null unique
);

alter table public.guests enable row level security;

create index if not exists idx_guests_acara on public.guests(acara_id);
create index if not exists idx_guests_qr_token on public.guests(qr_token);
create index if not exists idx_guests_status on public.guests(status_kehadiran);

-- 4. ACTIVITIES
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  action text not null,
  detail text not null,
  timestamp timestamptz default now(),
  user_id uuid references public.profiles(id)
);

alter table public.activities enable row level security;

create index if not exists idx_activities_timestamp on public.activities(timestamp desc);

-- RLS POLICIES (drop and recreate to be idempotent)

-- Profiles
drop policy if exists "Anyone can read profiles" on public.profiles;
create policy "Anyone can read profiles"
  on public.profiles for select
  using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Events
drop policy if exists "Anyone can read events" on public.events;
create policy "Anyone can read events"
  on public.events for select
  using (true);

drop policy if exists "Admin can insert events" on public.events;
create policy "Admin can insert events"
  on public.events for insert
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can update events" on public.events;
create policy "Admin can update events"
  on public.events for update
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin can delete events" on public.events;
create policy "Admin can delete events"
  on public.events for delete
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Guests
drop policy if exists "Admin, scanner and staff can read guests" on public.guests;
drop policy if exists "Admin and scanner can read guests" on public.guests;
create policy "Admin, scanner and staff can read guests"
  on public.guests for select
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'scanner', 'staff'))
  );

drop policy if exists "Admin can insert guests" on public.guests;
create policy "Admin can insert guests"
  on public.guests for insert
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Admin and scanner can update guests" on public.guests;
create policy "Admin and scanner can update guests"
  on public.guests for update
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'scanner'))
  );

drop policy if exists "Admin can delete guests" on public.guests;
create policy "Admin can delete guests"
  on public.guests for delete
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Activities
drop policy if exists "Users can read activities" on public.activities;
create policy "Users can read activities"
  on public.activities for select
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'scanner', 'staff'))
  );

drop policy if exists "Admin can insert activities" on public.activities;
create policy "Admin can insert activities"
  on public.activities for insert
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
    or auth.uid() is not null
  );

-- 5. FUNCTION: auto-create profile on user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, role, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'role', 'scanner'),
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
